spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root  
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Mudei de create-drop para update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: false

server:
  port: 8080  

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # um dia
      refresh-token:
        expiration: 604800000 #7dias